server:
  port: 8020

spring:
  mvc:
    servlet:
      path: /cykb
  elasticsearch:
    jest:
      uris: http://192.168.0.108:9200
      connection-timeout: 30000
      multi-threaded: true
      read-timeout: 7200

logging:
  level:
    root: warn
    com: info
  file:
    name: logs/cykb-es.log
